### ISSUE TITLE
Hardcoded options in adjust_tp

### ISSUE THREAD

**Issue by nopium** [Jimmy-sha256/SimpleFX_REST_API#1]
Hi! Thanks for the api - it works nice except adjust_tp:

I believe
`
        options = {
                "Login":572389,
                "Reality":"DEMO",
                "Id":order_id,
                "TakeProfit":tp
                }
`
Should be
`
        options = {
                "Login":self.account,
                "Reality":self.reality,
                "Id":order_id,
                "TakeProfit":tp
                }
`

**Comment by Jimmy-sha256** [comment]
Thanks for pointing this out.
